### ISSUE TITLE
Old version of socket.py

### ISSUE THREAD

**Issue by shsmad** [TasMania17/Gimp-Appimages-Made-From-Debs#1]
Hi, I'm trying to get working plugin `gimp-stable-diffusion-horde.py` from [blueturtleai/gimp-stable-diffusion](https://github.com/blueturtleai/gimp-stable-diffusion), it uses `urllib2` which uses `httplib` which uses `socket`.

In system-wide last version of python2.7 `socket.py` has lines:

```py
    from _ssl import \
         RAND_add, \
         RAND_status, \
         SSL_ERROR_ZERO_RETURN, \
         SSL_ERROR_WANT_READ, \
         SSL_ERROR_WANT_WRITE, \
         SSL_ERROR_WANT_X509_LOOKUP, \
         SSL_ERROR_SYSCALL, \
         SSL_ERROR_SSL, \
         SSL_ERROR_WANT_CONNECT, \
         SSL_ERROR_EOF, \
         SSL_ERROR_INVALID_ERROR_CODE
    try:
        from _ssl import RAND_egd
    except ImportError:
        # LibreSSL does not provide RAND_egd
        pass
``` 

but in your version it does not import RAND_egd in try/except:

```py
from _ssl import \
         RAND_add, \
         RAND_egd, \
         RAND_status, \
         SSL_ERROR_ZERO_RETURN, \
         SSL_ERROR_WANT_READ, \
         SSL_ERROR_WANT_WRITE, \
         SSL_ERROR_WANT_X509_LOOKUP, \
         SSL_ERROR_SYSCALL, \
         SSL_ERROR_SSL, \
         SSL_ERROR_WANT_CONNECT, \
         SSL_ERROR_EOF, \
         SSL_ERROR_INVALID_ERROR_CODE
```

so, it crashes because it can't import RAND_egd.

Can you update python2.7 to latest version? Or may be can I rebuild appimage with changes from your extracted appimage (didn't found any build instructions)?

**Comment by TasMania17** [comment]
On Windows Stable Diffusion uses Python 3.10.6
https://www.techspot.com/guides/2590-install-stable-diffusion/
The Gimp python2 launchers use the last python2 version (2.7.18)
https://stackoverflow.blog/2020/04/23/the-final-python-2-release-marks-the-end-of-an-era/
They are not designed for Python3 at all. Sorry.

**Comment by shsmad** [comment]
1. I'm using kubuntu 22.04 and your appimage
2. [SD gimp plugin](https://github.com/blueturtleai/gimp-stable-diffusion/blob/main/stablehorde/gimp-stable-diffusion-horde.py) uses python 2 & network requests (not running local instance, so no need of python3)

In my system-wide python I get:

```bash
$ python2 -V
Python 2.7.18

$ cat /usr/lib/python2.7/socket.py | grep RAND_egd -B 15 -A 3
    # we need to import the same constants we used to...
    from _ssl import SSLError as sslerror
    from _ssl import \
         RAND_add, \
         RAND_status, \
         SSL_ERROR_ZERO_RETURN, \
         SSL_ERROR_WANT_READ, \
         SSL_ERROR_WANT_WRITE, \
         SSL_ERROR_WANT_X509_LOOKUP, \
         SSL_ERROR_SYSCALL, \
         SSL_ERROR_SSL, \
         SSL_ERROR_WANT_CONNECT, \
         SSL_ERROR_EOF, \
         SSL_ERROR_INVALID_ERROR_CODE
    try:
        from _ssl import RAND_egd
    except ImportError:
        # LibreSSL does not provide RAND_egd
        pass

import os, sys, warnings
```

but in your appimage:

```bash
$ ./gimp-python2-overlay-launcher-ubuntu22.04.AppImage --appimage-mount
/tmp/.mount_gimp-p68vhfg

$ cat /tmp/.mount_gimp-p68vhfg/root/usr/lib/python2.7/socket.py | grep RAND_egd -B 5 -A 3

    # we need to import the same constants we used to...
    from _ssl import SSLError as sslerror
    from _ssl import \
         RAND_add, \
         RAND_egd, \
         RAND_status, \
         SSL_ERROR_ZERO_RETURN, \
         SSL_ERROR_WANT_READ, \
```

You have not the latest socket.py from python2.7.18

**Comment by TasMania17** [comment]
You can unpack the appimage and substitute the file. Use appimagetool from here:
https://appimage.github.io/appimagetool/

Unpack.
./gimp-python2-overlay-launcher-ubuntu22.04.AppImage --appimage-extract
copy file into the /usr tree and make sure permissions are the same as other files.
Repack.
./appimagetool-x86_64.AppImage ./squashfs-root/

**Comment by TasMania17** [comment]
Please let me know how you went?

**Comment by shsmad** [comment]
> Please let me know how you went?

I've repacked appimage successfully: replaced `ssl.py*` and `socket.py*` from my system `/usr/lib/python2.7`. Now everything works fine. 

Thanx for help.

**Comment by TasMania17** [comment]
Thanks for posting your results. I remember there were 'newer' versions of some of the ssl files but I chose to stick with the earlier ones due to security concerns on some distros. These appimages are working on possibly all linux versions. The reason they exist is because Gimp has never released python3 bindings while many Gimp users rely on python2 plug-ins.
Your project seems very worthwhile to me - good luck :)
