### ISSUE TITLE
Will it work on Ubuntu 23.04?

### ISSUE THREAD

**Issue by cmarchi** [TasMania17/Gimp-Appimages-Made-From-Debs#2]
Hi, will it work on Ubuntu 23.04? Thanks

**Comment by TasMania17** [comment]
Hi,
If  you open a terminal and enter 'gimp' it will probably work. If Gimp is installed as a flatpack then it already has python2 and you will not need the appimage. If gimp is installed as a snap then it probably will not work.
Could you get back on what you find?

**Comment by cmarchi** [comment]
Thanks, using flatpack from flathub.org worked. Neither snap from Ubuntu software and Gimp+gimp-plugin-registry through synaptic works.

**Comment by TasMania17** [comment]
Thanks for that,  If you have Filters > Python-fu > Console you have python2 and should be able to use the plug-ins.
